# Ansible Playbook to set up all that is required to run this rag demo with chromadb.
#
# Creates a new micromamba environmend called "rag-demo" with all required dependencies.
# Also loads all availible Markdown files into a chromDB vector database stored locally at rag-demo.db (workingdir)
#
# Parameters:
#   - ansible_user (string):      ssh-login user
#   - auto_start (bool):          whether the rag-demo should immediately start serving
#   - python_version (string):    use 3.11 for compatability
#   - micromamba_location (path): executable location for micromamba, should be in $PATH
#   - working_directory (path):   directory to put all related files.
#   - conda_dir (path):           conda root prefix
#   - model_repository (string):  The huggingface Reposotory to pull the model from
#   - model_name (string):        The name of the actual model/file (gguf) of the model in the model_repository.
#
- name: Micromamba Setup
  hosts: techzone
  tasks:
   - name: Ping hosts
     ansible.builtin.ping:

   - name: Create Working directory
     ansible.builtin.file:
      path: "{{ working_directory }}"
      state: directory
      owner: "{{ ansible_user }}"
      mode: u=rwx,g=rwx,o=rx
      recurse: true

   - name: "Check if micromamba already exists in {{ micromamba_location }}"
     ansible.builtin.stat:
      path: "{{ micromamba_location }}"
     register: dest_stat

   - name: Install required unzip tools
     become: true
     become_user: root
     ansible.builtin.dnf:
      name:
       - bzip2
       - git

   - name: Install micromamba
     ansible.builtin.import_tasks: download-and-extract-micromamba.yml
     when: not dest_stat.stat.exists

  vars: # required & referenced by `download-and-extract-micromamba.yml`
   arch: linux-ppc64le
   version: latest


- name: Mamba Environment
  hosts: techzone
  tasks:

   - name: Copying Environment file
     ansible.builtin.copy:
      src: rag-environment.yml
      dest: "{{ working_directory }}/rag-environment.yml"
      mode: a=r

   - name: Insert Python version into Environment file
     ansible.builtin.replace:
      path: "{{ working_directory }}/rag-environment.yml"
      regexp: "%{ python_version }%"
      replace: "{{ python_version }}"

   - name: Creating Environment
     ansible.builtin.command:
      argv:
       - micromamba
       - create
       - --root-prefix
       - "{{ conda_dir }}"
       - --yes
       - -f
       - "{{ working_directory }}/rag-environment.yml"

   - name: Copying requirements file
     ansible.builtin.copy:
      src: requirements.txt
      dest: "{{ working_directory }}/requirements.txt"
      mode: a=r

   - name: Install Pip requirements
     ansible.builtin.command:
      argv:
       - micromamba
       - run
       - --root-prefix
       - "{{ conda_dir }}"
       - -n
       - rag-demo
       - pip
       - install
       - -U
       - --extra-index-url
       - https://repo.fury.io/mgiessing
       - --prefer-binary
       - -r
       - "{{ working_directory }}/requirements.txt"

   - name: Clone Demo Reposotory
     ansible.builtin.git:
      repo: https://github.com/HenrikMader/RAG_public.git
      dest: "{{ working_directory }}/repo"
      clone: true
      update: true
      force: true
 
- name: Fill Database and start Server
  hosts: techzone
  tasks:
   - name: Download Model from huggingface
     ansible.builtin.command:
      argv:
       - micromamba
       - run
       - -n
       - rag-demo
       - --root-prefix
       - "{{ conda_dir }}"
       - huggingface-cli
       - download
       - "{{ model_repository }}"
       - "{{ model_name }}"
       - --local-dir
       - "{{ working_directory }}/model"
       - --local-dir-use-symlinks
       - "False"

   - name: Fill ChromaDB
     ansible.builtin.command:
      argv:
       - micromamba
       - run
       - -n
       - rag-demo
       - --root-prefix
       - "{{ conda_dir }}"
       - python
       - chromaDB_md.py
      chdir: "{{ working_directory }}/repo"

   - name: Run Model
     when: auto_start
     ansible.builtin.raw: |
      RAG_MODEL_PATH={{ working_directory }}/model/{{ model_name }} nohup micromamba run -n rag-demo --root-prefix {{ conda_dir }} python {{ working_directory }}/repo/run_model.py </dev/null >/dev/null 2>&1 & sleep 1
