# Ansible Playbook to set up all that is required to run this rag demo with chromadb.
#
# Creates a new micromamba environmend called "rag-demo" with all required dependencies.
# Also loads all availible Markdown files into a chromDB vector database stored locally at rag-demo.db (workingdir)
#
# Parameters:
#   - ansible_user (string):      ssh-login user
#   - auto_start (bool):          whether the rag-demo should immediately start serving
#   - python_version (string):    use 3.11 for compatability
#   - micromamba_location (path): executable location for micromamba, should be in $PATH
#   - working_directory (path):   directory to put all related files.
#   - conda_dir (path):           conda root prefix
#
- name: Micromamba Setup
  hosts: techzone
  tasks:
   - name: Ping hosts
     ansible.builtin.ping:

   - name: Create Working directory
     ansible.builtin.file:
      path: "{{ working_directory }}"
      state: directory
      owner: "{{ ansible_user }}"
      mode: u=rwx,g=rwx,o=rx
      recurse: true

   - name: "Check if micromamba already exists in {{ micromamba_location }}"
     ansible.builtin.stat:
      path: "{{ micromamba_location }}"
     register: dest_stat

   - name: Install required unzip tools
     become: true
     become_user: root
     ansible.builtin.dnf:
      name:
       - bzip2
     when: not dest_stat.stat.exists

   - name: Install micromamba
     ansible.builtin.import_tasks: download-and-extract-micromamba.yml
     when: not dest_stat.stat.exists

  vars: # required & referenced by `download-and-extract-micromamba.yml`
   arch: linux-ppc64le
   version: latest


- name: Mamba Environment
  hosts: techzone
  tasks:

   - name: Copying Environment file
     ansible.builtin.copy:
      src: rag-environment.yml
      dest: "{{ working_directory }}/rag-environment.yml"
      mode: a=r

   - name: Insert Python version into Environment file
     ansible.builtin.replace:
      path: "rag-environment.yml"
      regexp: "%{ python_verion }%"
      replace: "{{ python_version }}"

   - name: Creating Environment
     ansible.builtin.command:
      argv:
       - micromamba
       - create
       - --root-prefix
       - "{{ conda_dir }}"
       - --yes
       - -f
       - "{{ working_directory }}/rag-environment.yml"
